server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
    #mysql 连接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&charcterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml   #sql文件
  type-aliases-package: com.springcloud.entities  #实体类文件
#eureka 配置
eureka:
  client:
    #表示是否将自己注册到eureka中 默认true
    register-with-eureka: true
    #是否从eureka中抓取已有的注册信息 默认true  ===单节点无所谓，在集群中必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: pyament8001 #主机名称
    prefer-ip-address: true  #显示ip地址  访问信息有IP信息提示

