server:
  port: 9527


spring:
  application:
    name: cloude-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001  #匹配后提供服务的路由地址
        uri: lb://CLOUD-PAYMENT-SERVICE  #动态路由
        predicates:
        - Path=/payment/get/**  #断言,路径相匹配的进行路由
        #- After=2020-06-15T15:14:54.465+08:00[Asia/Shanghai]   #在日期时间之后可以
        #- Before=2020-06-15T15:14:54.465+08:00[Asia/Shanghai]  #在日期时间之前可以访问
        #- Between=2020-06-15T11:35:47.989+08:00[Asia/Shanghai], 2020-06-15T12:35:47.989+08:00[Asia/Shanghai]  #在日期时间之间可以访问
        #- Cookie=username,wang  #携带cookie才能访问
        #- Header=X-Request-Id, \d+   #携带请求头为 X-Request-Id  与 \d+ 正则匹配 才可以访问


      - id: payment_routh2
        #uri: http://localhost:8001
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/lb/**   #断言,路径相匹配的进行路由
        #- After=2020-06-15T16:14:54.465+08:00[Asia/Shanghai]   #在日期时间之后可以访问
        #- Before=2020-06-15T16:14:54.465+08:00[Asia/Shanghai]  #在日期时间之前可以访问
        #- Between=2020-06-15T15:35:47.989+08:00[Asia/Shanghai], 2020-06-15T16:35:47.989+08:00[Asia/Shanghai] #在日期时间之间可以访问
        #- Cookie=username,wang  #携带cookie才能访问 curl http://localhost:9527/payment/lb --cookie "username=wang"
        #- Header=X-Request-Id, \d+ #携带请求头为 X-Request-Id  与 \d+ 正则匹配 才可以访问
        #- Host=**.somehost.org,**.anotherhost.org #通过域名去匹配
        #- Method=GET #请求方法为get可以访问
        #- Query=username, \d+ #要有参数名称并且是正整数才能路由
        #Predicate就是为了实现一组匹配规则，让请求过来找到对应的Route进行处理
        filters:
        - AddRequestHeader=X-Request-Name, wangx




eureka:
  instance:
    hostname: cloude-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
