server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.153.128:1111   #集群模式 采用nginx代理
        server-addr: localhost:8848  #nacso地址 本地启动
  main:
    banner-mode: console
  banner:
    image:
      location: banner.txt
    charset: utf-8
#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"