server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.128:1111   #集群模式 采用nginx代理
        #server-addr: localhost:8848  #nacso地址 本地启动

service-url:
  nacos-user-service: http://nacos-payment-provider